build:
	javac *.java

run-best:
	java Test 3

run-p1:
	java Test 1

run-p2:
	java Test 2

run-p3:
	java Test 3

run-best-all:
	java Main 3

run-p1-all:
	java Main 1

run-p2-all:
	java Main 2

run-p3-all:
	java Main 3

tests:
	java TestGenerator

clean:
	rm -rf *.class